ingress:
  enabled: true
  hosts:
    - grafana.test.com
persistence:
  type: pvc
  enabled: true
  size: 30Gi
datasources: 
  datasources:
  - name: Prometheus
    type: prometheus
    url: http://prometheus-server.monitoring.svc.cluster.local
    isDefault: true
  - name: Loki
    type: loki
    url: http://loki-gateway.monitoring.svc.cluster.local
  
