values:
  loki:
    auth_enabled: false
    storage:
      type: s3
      s3:
        region: region-name
        s3ForcePathStyle: false
        insecure: false
      bucketNames:
        chunks: bucket-name
        ruler: bucket-name
        admin: bucket-name
  write: 
    extraEnvFrom:
      - secretRef:
          name: secret-name    # contains AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY
  read:
    extraEnvFrom:
      - secretRef:
          name: secret-name    # contains AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY
  backend:
    extraEnvFrom:
      - secretRef:
          name: secret-name    # contains AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY
  schema_config:
    configs:
    - from: 2023-06-01
      store: aws
      object_store: s3
      schema: v11
      index:
        prefix: loki_
  storage_config:
    aws:
      bucketnames: bucket-name
      region: region-name
      access_key_id: 
      secret_access_key: 
      insecure: false
      sse_encryption: false
      http_config:
        idle_conn_timeout: 90s
        response_header_timeout: 0s
          insecure_skip_verify: false
        s3forcepathstyle: true
    
